version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_sk
        tests: [unique, not_null]
      - name: customer_nk
        tests: [not_null]
  - name: dim_product
    columns:
      - name: product_sk
        tests: [unique, not_null]
  - name: dim_date
    columns:
      - name: date_sk
        tests: [unique, not_null]
  - name: fct_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_sk
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_sk
  - name: fct_order_items
    columns:
      - name: order_line_id
        tests: [unique, not_null]
  - name: fct_shipments
    columns:
      - name: shipment_id
        tests: [unique, not_null]
